import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://projects.owesome.work/');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.locator('div').filter({ hasText: /^Email$/ }).click();
    await page.getByRole('textbox', { name: 'Email' }).dblclick();
    await page.getByRole('textbox', { name: 'Email' }).fill('usmanali@ikonicsolution.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('Usmanalidev@2005');
    await page.getByText('Remember me').click();
    await page.getByRole('button', { name: 'Show password' }).click();
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('treeitem', { name: 'Development' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).dblclick();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).dblclick();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Saraan - Projects' }).click();
    await page.getByRole('treeitem', { name: 'Lawyer.AI' }).click();
    await page.getByRole('button', { name: 'Board', exact: true }).click();
    await page.getByText('BACKLOG0 Add TaskON HOLD0 Add').click();
    await page.getByRole('button', { name: 'Add Task', exact: true }).nth(3).click();
    await page.getByRole('textbox', { name: 'Task name...' }).fill('Work on Claude Connectors ');
    await page.getByRole('button', { name: 'Add', exact: true }).click();
    await page.getByRole('button', { name: 'Work on Claude Connectors Normal Task options for Work on Claude Connectors' }).click();
    await page.getByRole('button', { name: 'Empty' }).nth(1).click();
    await page.getByRole('button', { name: 'Today Mon' }).click();
    await page.getByRole('button', { name: 'Today Mon' }).click();
    await page.getByRole('button', { name: 'Today Mon' }).click();
    await page.getByText('Task ID-29645', { exact: true }).click();
    await page.getByRole('button', { name: 'Empty' }).first().click();
    await page.getByRole('button', { name: 'Usman Ali Me usmanali@' }).click();
    await page.getByRole('button', { name: 'Empty' }).click();
    await page.getByRole('button', { name: '3h' }).click();
    await page.getByRole('button', { name: ':00:00' }).click();
    await page.getByTestId('track-time-duration-input').click();
    await page.getByTestId('track-time-duration-input').fill('3h');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.locator('div').filter({ hasText: 'StatusIN PROGRESS - DEVAssigneesUsman AliDatesTodayTodayPriorityNormalTime' }).nth(4).click();
    await page.getByRole('button', { name: 'Add description' }).click();
    await page.locator('.tiptap').first().fill('dummy description');
    await page.getByPlaceholder('—').first().click();
    await page.getByPlaceholder('—').first().fill('3');
    await page.locator('div').filter({ hasText: /^\$Billable Hrs$/ }).first().click();
    await page.getByRole('paragraph').filter({ hasText: /^$/ }).click();
    await page.locator('.tiptap.ProseMirror.prose.prose-sm.max-w-none.focus\\:outline-none.text-\\[14px\\].leading-relaxed.cursor-text.break-words.\\[overflow-wrap\\:anywhere\\].dark\\:text-white.dark\\:\\[\\&_p\\]\\:text-white.dark\\:\\[\\&_li\\]\\:text-white.dark\\:\\[\\&_h1\\]\\:text-white.dark\\:\\[\\&_h2\\]\\:text-white.dark\\:\\[\\&_strong\\]\\:text-white.dark\\:\\[\\&_em\\]\\:text-white.px-3').fill('task report:\ndummy task report');
    await page.getByRole('button', { name: 'Send' }).click();
});